function uOpt = MyMinLS2hp(uo,m,muRef,y,ModelConfig,DataConfig,RTOConfig)
func = @(u)funcF2hp(u,m,muRef,y,ModelConfig,DataConfig);
options = optimoptions('lsqnonlin','Algorithm','trust-region-reflective', ...
    'SpecifyObjectiveGradient',false, ...
    'Diagnostics','off', ...
    'Display','off');
uOpt = lsqnonlin(func, uo, RTOConfig.muBounds(1), RTOConfig.muBounds(2), options);